### ISSUE TITLE
failed to open

### ISSUE THREAD

**Issue by bozo32** [flurb18/AgentOoba#11]
ERROR:Failed to load the extension "AgentOoba".
Traceback (most recent call last):
  File "/home/.../ai/text-generation-webui/modules/extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/.../ai/text-generation-webui/extensions/AgentOoba/script.py", line 13, in <module>
    CTX_MAX = int(os.getenv("CTX_MAX"))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by flurb18** [comment]
Copy and paste .env.example to .env in the project folder. Modify it if you wish.

**Comment by bozo32** [comment]
oh I am a TWIT.
I'm working on scientific linux on a cluster if there is anything funky you want to try out.
