### ISSUE TITLE
Trying to add new tools, I always get errors

### ISSUE THREAD

**Issue by juangea** [flurb18/AgentOoba#13]
Hi there.

I'm trying to add several langchain tools, but I get errors and it is incapable of loading them, for example this is the list of tools I put in the code:

`KNOWN_TOOLS = ["wikipedia", "searx-search", "requests_get", "requests_post","ShellTool","ReadFileTool","CopyFileTool","DeleteFileTool","MoveFileTool","WriteFileTool","ListDirectoryTool","human"]
`
I give the corresponding descriptions and before this I do the imports:

```
from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.llms.base import LLM
from langchain.agents import load_tools
from langchain.tools import Tool
from langchain.tools import DuckDuckGoSearchRun
from langchain.tools import ShellTool
from langchain.agents.agent_toolkits import FileManagementToolkit
from tempfile import TemporaryDirectory
from langchain.agents import load_tools, initialize_agent
from langchain.agents import AgentType
```

But then I get this error (this is one, but I get this for any tool that is not by default in your code):

`ValueError: Got unknown tool ShellTool`

So what am I doing wrong, I think I'm not using the correct tool name or something, but I'm looking for it in langchain docs and I can't find the solution.

Thanks!

**Comment by juangea** [comment]
Also I'm not sure how to make it use the existing tools, it makes up things:

`OBJECTIVE: You can use requests_get Tell me the headline of the first article you can find at https://www.cgpress.org and write a tweet about it.`

`MODEL OUTPUT The headline of the first article I found from <https://www.cgpress.org> is "How To Use React For Web Development". Here's my tweet about it: "Just learned about reactjs! Check out this guide by @cgpress on how to get started with web development."</s>`

This is false, cgpress is a website about 3d, and the first headline is "[Maxon One May updates Redshift, Cineware for Unreal and Cinema4D](https://cgpress.org/archives/maxon-one-may-updates-redshift-cineware-for-unreal-and-cinema4d.html)" so I'm doing something wrong probably.

**Comment by murmur9283** [comment]
I am not even sure it uses the tools. I let it work for hours on "Who is Napoleon" and it evaluated the built-in tools and  evaluated the tools with "yes" but was then not able to generate a prompt (cannot). Finally it made something up.

**Comment by juangea** [comment]
That's what is happening to me, it says it's gonna use the tools, but then it makes things up.
Also what I'm saying about not being able to add tools.

**Comment by flurb18** [comment]
Yeah I think the given langchain descriptions of the tools aren't good enough. I'll have to write custom descriptions so it knows how to use them.

**Comment by flurb18** [comment]
Also, in the KNOWN_TOOLS list, make sure to use the official langchain tool code, I found some [here](https://python.langchain.com/en/latest/modules/agents/tools/getting_started.html), note that in the KNOWN_TOOLS list it should be the heading of the tool not the subheading "tool name", so "wikipedia" not "Wikipedia" and "searx-search" not "Searx Search". For custom tools you might have to declare it yourself and put it into the Tools list.

**Comment by juangea** [comment]
I tried in several ways, for example I tried with everything I found here for the duckduckgosearch:
https://python.langchain.com/en/latest/modules/agents/tools/examples/ddg.html

Nothing worked, no matter what do I use, it always says the tool is unknown.

The same goes for the Shell Tool, no matter what do I use, I've looked in the documentation page for that tool, and nothing worked.

Also, is the description important for the LLM so it can use the tool?

**Comment by juangea** [comment]
This in an error example:

```
INFO:Loading the extension "AgentOoba"...
ERROR:Failed to load the extension "AgentOoba".
Traceback (most recent call last):
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\extensions\AgentOoba\script.py", line 135, in <module>
    Tools = load_tools(
  File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\langchain\agents\load_tools.py", line 416, in load_tools
    raise ValueError(f"Got unknown tool {name}")
ValueError: Got unknown tool duckduckgo-search
```

**Comment by ice0** [comment]
> This in an error example:
> 
> ```
> INFO:Loading the extension "AgentOoba"...
> ERROR:Failed to load the extension "AgentOoba".
> Traceback (most recent call last):
>   File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
>     exec(f"import extensions.{name}.script")
>   File "<string>", line 1, in <module>
>   File "D:\AI\oobabooga\oobabooga_windows\text-generation-webui\extensions\AgentOoba\script.py", line 135, in <module>
>     Tools = load_tools(
>   File "D:\AI\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\langchain\agents\load_tools.py", line 416, in load_tools
>     raise ValueError(f"Got unknown tool {name}")
> ValueError: Got unknown tool duckduckgo-search
> ```

Have you installed it?
```
pip install duckduckgo-search
```

**Comment by juangea** [comment]
Yes, that's the first thing I did, in my general invironment (pure windows CMD) and in the ooba environment.

But it does not matter, you can try with whatever other tool you want, like shell tools, and you will get the same error.

**Comment by daouid** [comment]
Would be great to have it use EdgeGPT extension and "Hey Bing" keyword when needed to access internet info
https://github.com/GiusTex/EdgeGPT

**Comment by Terramoto** [comment]
I've managed to implement more tools via:
````
Tools = [
    Tool(
        name="python",
        func=python_tool.run,
        description="A Python shell. Use this to execute python commands. Input should be a valid python command. If you expect output it should be printed out."
    ),
    Tool(
        name="cmd",
        func=shell_tool.run,
        description="A windows terminal. Use this to execute windows commands. Input should be a valid windows command prompt command."
    ),
    Tool(
        name="wikipedia",
        func=wikipedia.run,
        description="A collection of articles on various topics. Used when the task at hand is researching or acquiring general surface-level information about any topic. Input is a topic; the tool will then save general information about the topic to memory."
    ),
    Tool(
        name="request_get",
        func=requests_tools.get,
        description="A portal to the internet. Use this when you need to get specific content from a website. Input should be a  url (i.e. https://www.google.com). The output will be the text response of the GET request."
    ),
    Tool(
        name="request_post",
        func=requests_tools.post,
        description='Use this when you want to POST to a website.\n    Input should be a json string with two keys: "url" and "data".\n    The value of "url" should be a string, and the value of "data" should be a dictionary of \n    key-value pairs you want to POST to the url.\n    Be careful to always use double quotes for strings in the json string\n    The output will be the text response of the POST request.'
    ),
	Tool(
		name="search",
		func=duck_tool.run,
		description='A URL search engine. Used when the task at hand is searching the internet for websites that mention a certain topic. useful for when you need to answer questions about current events. Input is a search query; the tool will then save URLs for popular websites that reference the search query to memory.'
		)
]
```

**Comment by juangea** [comment]
@Terramoto Have you got the system to actually work? 

I never get anything useful from it.

**Comment by Terramoto** [comment]
the model is calling for the tool and providing the input, i can even get output from the commands but the input is not being properly filtered. For example:
```
raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'request_get "https://www.timeanddate.com/worldclock/"'
```
it looks like the whole input string is being sent to the command, but this is after the model calls for the command with the input so i would assume this would be an issue with the extension when extracting the command and args from the string.

**Comment by juangea** [comment]
Then something probably for @flurb18 

It's a pity not having this extension working, it could something pretty awesome, and I don't know of any other extension that can work with Langchain properly, only CPU implementations

**Comment by Terramoto** [comment]
Managed to get it working, but my lack of experience in Python translates into a poor line of code:
Objectives.py(182):
```
                directive = AgentOobaVars["directives"]["Summarize directive"].replace(
                    "_TEXT_", doc.page_content)
```
doc is a document containing both page_content and metadata which by attempting to replace will report an error about not being a string.

Objectives.py(206):
```
if(tool.name == "request_get" or tool.name == "request_post"):
                    tool_input = re.findall(r'(https?://\S+)', tool_input)[0]
                    tool_input = ''.join(tool_input)
                    tool_input = tool_input.strip("><")
```
This was just a way i found to extract the actual input from the tool_input which for some reason, for me, was returning the tool_name and the input, so it would end up calling ie: request_get 'request_get <http://lalala.com/>' which would fail. with this  it will extract only the url.

If you find a better way, please let me know.
