### ISSUE TITLE
Error when loading extension: "TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'"

### ISSUE THREAD

**Issue by Fluorax** [flurb18/AgentOoba#5]
Hello,

I encountered an error when trying to load the "AgentOoba" extension. Here's the traceback:

```
ERROR: Failed to load the extension "AgentOoba".
Traceback (most recent call last):
  File "/media/ultrastar/ai/text-generation-webui/modules/extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/media/ultrastar/ai/text-generation-webui/extensions/AgentOoba/script.py", line 12, in <module>
    CTX_MAX = int(os.getenv("CTX_MAX"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
```

Also note that I am getting an error when installing requirements.

```
pip install -r requirements.txt             
Requirement already satisfied: langchain in /media/ultrastar/ai/miniconda3/envs/textgen/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.0.163)
Requirement already satisfied: typing in /media/ultrastar/ai/miniconda3/envs/textgen/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (3.7.4.3)
Requirement already satisfied: wikipedia in /media/ultrastar/ai/miniconda3/envs/textgen/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: wolframalpha in /media/ultrastar/ai/miniconda3/envs/textgen/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (5.0.0)
Requirement already satisfied: chromadb in /media/ultrastar/ai/miniconda3/envs/textgen/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.3.22)
Collecting dotenv (from -r requirements.txt (line 6))
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      /home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-1owujx1a/distribute_5e9ce65159654c018989baad3bb99834/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-1owujx1a/distribute_5e9ce65159654c018989baad3bb99834/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-1owujx1a/distribute_5e9ce65159654c018989baad3bb99834/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-1owujx1a/distribute_5e9ce65159654c018989baad3bb99834/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-1owujx1a/distribute_5e9ce65159654c018989baad3bb99834/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-1owujx1a/distribute_5e9ce65159654c018989baad3bb99834/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home_dir/ai/miniconda3/envs/textgen/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpy_fx6drz', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vffsnm1_/dotenv_195539a886ca44d1a156e1dd62b9d491/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/home_dir/ai/miniconda3/envs/textgen/lib/python3.9/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home_dir/ai/miniconda3/envs/textgen/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpy_fx6drz', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

It appears that the code is expecting an environment variable named "CTX_MAX", but this variable is not set. As a result, os.getenv("CTX_MAX") returns None, and int(None) raises a TypeError.

It would be helpful if the code could handle the case where "CTX_MAX" is not set. For instance, it could provide a default value:

`CTX_MAX = int(os.getenv("CTX_MAX", "default_value"))`

Please replace "default_value" with a suitable default value for "CTX_MAX". Alternatively, the documentation could specify that users need to set the "CTX_MAX" environment variable and provide instructions on how to do so.

Thanks for looking into this!

EDIT:
Issue fixed by running: `cp -iv .env.example .en`

**Comment by flurb18** [comment]
Yeah new .env file, contains all defaults
