### ISSUE TITLE
dotenv json requirements do not work and throw errors

### ISSUE THREAD

**Issue by waefrebeorn** [flurb18/AgentOoba#6]
dotenv
Collecting dotenv (from -r .\requirements.txt (line 6))
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      L:\conda\lib\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [16 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 14, in <module>
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-mif_8m8p\distribute_47a2eefd95834065a3f894fb68c6ab1b\setuptools\__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-mif_8m8p\distribute_47a2eefd95834065a3f894fb68c6ab1b\setuptools\extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-mif_8m8p\distribute_47a2eefd95834065a3f894fb68c6ab1b\setuptools\dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-mif_8m8p\distribute_47a2eefd95834065a3f894fb68c6ab1b\setuptools\command\__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-mif_8m8p\distribute_47a2eefd95834065a3f894fb68c6ab1b\setuptools\command\install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-mif_8m8p\distribute_47a2eefd95834065a3f894fb68c6ab1b\pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "L:\conda\lib\site-packages\setuptools\installer.py", line 97, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "L:\conda\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['L:\\conda\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\eman5\\AppData\\Local\\Temp\\tmpqtv5azec', '--quiet', 'distribute']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\eman5\AppData\Local\Temp\pip-install-gd445qej\dotenv_baa48453d8e2406e81d80e0ee0f89389\setup.py", line 13, in <module>
          setup(name='dotenv',
        File "L:\conda\lib\site-packages\setuptools\__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "L:\conda\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "L:\conda\lib\site-packages\setuptools\__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "L:\conda\lib\site-packages\setuptools\dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "L:\conda\lib\site-packages\setuptools\installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 1145, in obtain
          return installer(requirement)
        File "L:\conda\lib\site-packages\setuptools\installer.py", line 99, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['L:\\conda\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\eman5\\AppData\\Local\\Temp\\tmpqtv5azec', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(base) PS K:\1ai\oog\oobabooga-windows\text-generation-webui\extensions\AgentOoba> pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      L:\conda\lib\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [16 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 14, in <module>
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-yzvca0l0\distribute_aea3303093ff4f62b26dce5175fe64e5\setuptools\__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-yzvca0l0\distribute_aea3303093ff4f62b26dce5175fe64e5\setuptools\extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-yzvca0l0\distribute_aea3303093ff4f62b26dce5175fe64e5\setuptools\dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-yzvca0l0\distribute_aea3303093ff4f62b26dce5175fe64e5\setuptools\command\__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-yzvca0l0\distribute_aea3303093ff4f62b26dce5175fe64e5\setuptools\command\install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "C:\Users\eman5\AppData\Local\Temp\pip-wheel-yzvca0l0\distribute_aea3303093ff4f62b26dce5175fe64e5\pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "L:\conda\lib\site-packages\setuptools\installer.py", line 97, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "L:\conda\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['L:\\conda\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\eman5\\AppData\\Local\\Temp\\tmp_oesvrv9', '--quiet', 'distribute']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\eman5\AppData\Local\Temp\pip-install-dlem1ttv\dotenv_67915a41431147818f8feb05eb5174e1\setup.py", line 13, in <module>
          setup(name='dotenv',
        File "L:\conda\lib\site-packages\setuptools\__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "L:\conda\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "L:\conda\lib\site-packages\setuptools\__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "L:\conda\lib\site-packages\setuptools\dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "L:\conda\lib\site-packages\setuptools\installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "L:\conda\lib\site-packages\pkg_resources\__init__.py", line 1145, in obtain
          return installer(requirement)
        File "L:\conda\lib\site-packages\setuptools\installer.py", line 99, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['L:\\conda\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\eman5\\AppData\\Local\\Temp\\tmp_oesvrv9', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
json

ERROR: Ignored the following versions that require a different python version: 3.10.0.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.5; 3.7.4.2 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.5
ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json
in requirments halt the install of requirements

manually installing dotenv works but there is no repo in pip for json

**Comment by flurb18** [comment]
Whoops I guess json is built in. Will remove from requirements
