### ISSUE TITLE
occur error when install requirement package dotenv

### ISSUE THREAD

**Issue by kanslor** [flurb18/AgentOoba#7]
I use the conda environment,python version 3.10.9, when I exectue `pip install -r requirement.txt` occurs the error.

```
Collecting dotenv (from -r requirements.txt (line 6))
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      /home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-4_e44bv7/distribute_789d4844bd21483ba4d2eed22e22534b/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-4_e44bv7/distribute_789d4844bd21483ba4d2eed22e22534b/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-4_e44bv7/distribute_789d4844bd21483ba4d2eed22e22534b/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-4_e44bv7/distribute_789d4844bd21483ba4d2eed22e22534b/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-4_e44bv7/distribute_789d4844bd21483ba4d2eed22e22534b/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-4_e44bv7/distribute_789d4844bd21483ba4d2eed22e22534b/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/isoface/anaconda3/envs/textgen/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpv_yshx_r', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-eej6j084/dotenv_5920fc86e3454fcebef593d54cd63f66/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
          dist = self._resolve_dist(
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1123, in best_match
          return self.obtain(req, installer)
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in obtain
          return installer(requirement)
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/isoface/anaconda3/envs/textgen/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/isoface/anaconda3/envs/textgen/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpv_yshx_r', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by kanslor** [comment]
I chage the requirement.txt `dotenv` to `python-dotenv` to solve... Is the same package?

**Comment by kanslor** [comment]
sorry I forgot to check the closed issue

**Comment by kanslor** [comment]
but the dotenv still exists... so i reopend it 😀

**Comment by flurb18** [comment]
Sorry, it seems the package is named python-dotenv, rather than dotenv. Updating requirements

**Comment by flurb18** [comment]
Should be fixed now
